### ISSUE TITLE
Safari has a error on game start

### ISSUE THREAD

**Issue by mrsteele** [woofers/react-pico-8#63]
Hey, thanks for a great start to supporting PICO-8 embeds in our React apps!

I noticed that on safari, I get an error:

> RangeError. duration value should be positive

The bug happens exactly when you click the "play" button on the games. Works perfectly fine in Chrome but seems to be specific to Safari (which includes iphones).

**Comment by woofers** [comment]
Hi @mrsteele,  thanks for reporting this issue.

I was able to reproduce the exact issue in Midori, a Linux based webkit browser (Unfortunatly, I don't have access to a Mac).
It seems to be caused by some `AudioContext` API differences with Safari.  (https://stackoverflow.com/a/55730826)

I have pushed `v3.3.1` to NPM with a patch (585f617) that resolved the issue for me and allowed carts to played.

Please let me know if this has resolved your issue and if it does I will close this out.

Also feel free to let me know if you find any other issues in Safari.

**Comment by mrsteele** [comment]
Yup! That resolved it for sure.

Thanks for getting that taken care of!

**Comment by woofers** [comment]
@mrsteele Awesome that's great to hear.  Glad we could resolve it.
